"""
make_notebook.py — Emit a parameterized OlmoEarth embeddings notebook.

The generated notebook mirrors the AllenAI AWF Kenya tutorial's embeddings
workflow but with the user's dataset path, class taxonomy, and model size
baked into the configuration cell. The user is expected to read the notebook,
not just run it — comments call out the parts most likely to need adapting.

Usage:
    python make_notebook.py \
        --dataset-path /path/to/rslearn_dataset \
        --num-classes 9 \
        --class-names "tree_cover,shrubs,cropland,builtup,bare,grassland,water,wetland,other" \
        --model nano \
        --out my_embeddings_workflow.ipynb

The output is a valid .ipynb (Jupyter notebook v4) that runs end-to-end
on Colab T4 / local CUDA / Apple Silicon MPS / CPU. Stdlib only on the
generation side; the notebook itself needs olmoearth_pretrain + rslearn +
scikit-learn at runtime.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

MODEL_IDS = {
    "nano": ("OLMOEARTH_V1_NANO", 128),
    "tiny": ("OLMOEARTH_V1_TINY", 192),
    "base": ("OLMOEARTH_V1_BASE", 768),
    "large": ("OLMOEARTH_V1_LARGE", 1024),
}


def md(text: str) -> dict:
    """Markdown cell."""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": text.splitlines(keepends=True),
    }


def code(text: str) -> dict:
    """Code cell."""
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


def build_notebook(dataset_path: str, num_classes: int, class_names: list[str],
                   model: str, train_group: str, val_group: str,
                   nodata_value: int, knn_k: int) -> dict:
    model_const, emb_dim = MODEL_IDS[model]
    class_names_repr = json.dumps(class_names)

    cells = []

    cells.append(md(
        f"# OlmoEarth Embeddings — Workflow Notebook\n"
        f"\n"
        f"Generated by `olmoearth-embeddings/scripts/make_notebook.py`.\n"
        f"\n"
        f"Mirrors the AllenAI AWF Kenya tutorial's embeddings flow, "
        f"parameterized for **your** dataset:\n"
        f"\n"
        f"- **Dataset path**: `{dataset_path}`\n"
        f"- **Classes** ({num_classes}): {', '.join(class_names)}\n"
        f"- **Model**: OlmoEarth {model.capitalize()} (~{emb_dim}-dim embeddings)\n"
        f"\n"
        f"### What this notebook does\n"
        f"\n"
        f"1. Loads the OlmoEarth {model.capitalize()} encoder (frozen).\n"
        f"2. Extracts a feature vector per labeled window.\n"
        f"3. Trains a kNN classifier and a linear probe on the embeddings.\n"
        f"4. Reports val accuracy + confusion matrix for both.\n"
        f"\n"
        f"### Read before running\n"
        f"\n"
        f"- The `BANDSET_INFO` and `BAND_NAMES` constants assume Sentinel-2 with 3 bandsets "
        f"(10 m, 20 m, 60 m). If your `dataset.json` uses a different layout — e.g., the "
        f"production-style 12-monthly layers — edit cell 4.\n"
        f"- The window groups are `{train_group}` and `{val_group}`. Edit cell 3 if your "
        f"groups are named differently.\n"
        f"- Nodata pixels in the label raster are assumed to be `{nodata_value}`. Change "
        f"`NODATA_VALUE` if not.\n"
    ))

    cells.append(md("## 1. Install + import"))

    cells.append(code(
        "# Install (Colab / fresh env). Skip if your env already has these.\n"
        "!pip install -q olmoearth_pretrain rslearn scikit-learn rasterio einops scipy tqdm matplotlib"
    ))

    cells.append(code(
        "import os\n"
        "\n"
        "# Apple Silicon: allow MPS fallback for ops the backend doesn't support yet.\n"
        '# Must be set before importing torch.\n'
        'os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")\n'
        "\n"
        "import json\n"
        "from collections import Counter\n"
        "from pathlib import Path\n"
        "\n"
        "import numpy as np\n"
        "import torch\n"
        "import rasterio\n"
        "from einops import rearrange\n"
        "from scipy.ndimage import zoom\n"
        "from tqdm.auto import tqdm\n"
        "\n"
        "from sklearn.neighbors import KNeighborsClassifier\n"
        "from sklearn.linear_model import LogisticRegression\n"
        "from sklearn.preprocessing import StandardScaler, normalize\n"
        "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix\n"
        "\n"
        "from rslearn.dataset import Dataset\n"
        "from upath import UPath\n"
        "\n"
        "from olmoearth_pretrain.model_loader import ModelID, load_model_from_id\n"
        "from olmoearth_pretrain.datatypes import MaskedOlmoEarthSample, MaskValue\n"
        "from olmoearth_pretrain.data.normalize import load_computed_config\n"
        "\n"
        "\n"
        "def get_device():\n"
        '    if torch.cuda.is_available(): return torch.device("cuda")\n'
        '    if torch.backends.mps.is_available(): return torch.device("mps")\n'
        '    return torch.device("cpu")\n'
        "\n"
        "device = get_device()\n"
        'print(f"Device: {device}")'
    ))

    cells.append(md("## 2. Configuration\n\nEdit these values to match your dataset."))

    cells.append(code(
        f"# === GENERATED CONFIG — edit if needed =====================================\n"
        f"DATASET_PATH = UPath({dataset_path!r})\n"
        f"NUM_CLASSES = {num_classes}\n"
        f"CLASS_NAMES = {class_names_repr}\n"
        f"NODATA_VALUE = {nodata_value}\n"
        f"\n"
        f'TRAIN_GROUP = "{train_group}"\n'
        f'VAL_GROUP   = "{val_group}"\n'
        f"\n"
        f"MODEL_ID = ModelID.{model_const}\n"
        f"EMBEDDING_DIM = {emb_dim}\n"
        f"\n"
        f"KNN_K = {knn_k}\n"
        f"\n"
        f"# Sentinel-2 layout (3 bandsets at 10 m / 20 m / 60 m — AWF tutorial style).\n"
        f"# If your dataset.json uses the production layout (12 monthly layers, single bandset),\n"
        f"# replace this block — see references/rslearn_config.md in olmoearth-data-prep.\n"
        f'BANDSET_INFO = [("R_G_B_NIR", 4), ("RE1_RE2_RE3_RE4_SWIR1_SWIR2", 6), ("AERO_WV", 2)]\n'
        f'BAND_NAMES = ["B02","B03","B04","B08","B05","B06","B07","B8A","B11","B12","B01","B09"]\n'
        f"MAX_TIMESTEPS = 12\n"
        f"# ===========================================================================\n"
    ))

    cells.append(md("## 3. Load the rslearn dataset and split windows"))

    cells.append(code(
        "dataset = Dataset(DATASET_PATH)\n"
        "all_windows = dataset.load_windows()\n"
        'print(f"Total windows: {len(all_windows)}")\n'
        "\n"
        "train_windows = [w for w in all_windows if w.group == TRAIN_GROUP]\n"
        "val_windows   = [w for w in all_windows if w.group == VAL_GROUP]\n"
        'print(f"Train: {len(train_windows)} | Val: {len(val_windows)}")\n'
        "\n"
        "assert len(train_windows) > 0, f\"No windows in group {TRAIN_GROUP!r}. Edit TRAIN_GROUP.\"\n"
        "assert len(val_windows)   > 0, f\"No windows in group {VAL_GROUP!r}. Edit VAL_GROUP.\""
    ))

    cells.append(md(
        "## 4. Helpers: normalize + load window + extract embedding\n"
        "\n"
        "These are copied from the AWF tutorial verbatim — the model expects exactly "
        "this preprocessing. Edit only if your dataset deviates from the 3-bandset S2 layout."
    ))

    cells.append(code(
        "NORM_CONFIG = load_computed_config()['sentinel2_l2a']\n"
        "\n"
        "def normalize_sentinel2(data, std_multiplier=2):\n"
        "    data = data.astype(np.float32).copy()\n"
        "    T, C, H, W = data.shape\n"
        "    for t in range(T):\n"
        "        for c, name in enumerate(BAND_NAMES):\n"
        "            if name in NORM_CONFIG:\n"
        "                mean = NORM_CONFIG[name]['mean']\n"
        "                std  = NORM_CONFIG[name]['std']\n"
        "                lo = mean - std_multiplier * std\n"
        "                hi = mean + std_multiplier * std\n"
        "                data[t, c] = (data[t, c] - lo) / (hi - lo)\n"
        "    return np.clip(data, 0, 1)\n"
        "\n"
        "def load_window_data(window, dataset_path):\n"
        "    window_root = window.get_window_root(dataset_path, window.group, window.name)\n"
        '    layers_dir = window_root / "layers"\n'
        "    timesteps = []\n"
        "    for t in range(MAX_TIMESTEPS):\n"
        '        layer = "sentinel2" if t == 0 else f"sentinel2.{t}"\n'
        "        layer_dir = layers_dir / layer\n"
        "        if not layer_dir.exists():\n"
        "            continue\n"
        "        bandset_data = []\n"
        "        target_size = None\n"
        "        for bandset_name, _ in BANDSET_INFO:\n"
        '            path = layer_dir / bandset_name / "geotiff.tif"\n'
        "            if path.exists():\n"
        "                with rasterio.open(str(path)) as src:\n"
        "                    data = src.read()\n"
        "                    if target_size is None:\n"
        "                        target_size = data.shape[1:]\n"
        "                    if data.shape[1:] != target_size:\n"
        "                        factors = (1, target_size[0]/data.shape[1], target_size[1]/data.shape[2])\n"
        "                        data = zoom(data, factors, order=1)\n"
        "                    bandset_data.append(data)\n"
        "        if len(bandset_data) == 3:\n"
        "            timesteps.append(np.concatenate(bandset_data, axis=0))\n"
        "    if not timesteps:\n"
        "        return None, None\n"
        "    s2 = normalize_sentinel2(np.stack(timesteps, axis=0))\n"
        "\n"
        '    label_path = layers_dir / "label" / "category" / "geotiff.tif"\n'
        "    label = None\n"
        "    if label_path.exists():\n"
        "        with rasterio.open(str(label_path)) as src:\n"
        "            arr = src.read(1)\n"
        "            uniq = np.unique(arr)\n"
        "            valid = uniq[(uniq != NODATA_VALUE) & (uniq < NUM_CLASSES)]\n"
        "            if len(valid) > 0:\n"
        "                label = int(valid[0])\n"
        "    return s2, label\n"
        "\n"
        "def extract_embedding(encoder, s2, device, patch_size=4):\n"
        "    T, C, H, W = s2.shape\n"
        "    tensor = torch.from_numpy(s2.astype(np.float32)).to(device)\n"
        "    tensor = rearrange(tensor, 't c h w -> 1 h w t c')\n"
        "    mask = torch.full((1, H, W, T, 3), MaskValue.ONLINE_ENCODER.value,\n"
        "                      dtype=torch.int32, device=device)\n"
        "    timestamps = torch.zeros((1, T, 3), dtype=torch.int32, device=device)\n"
        "    timestamps[0, :, 1] = torch.arange(T, device=device)\n"
        "    sample = MaskedOlmoEarthSample(\n"
        "        sentinel2_l2a=tensor,\n"
        "        sentinel2_l2a_mask=mask,\n"
        "        timestamps=timestamps,\n"
        "    )\n"
        "    with torch.no_grad():\n"
        "        out = encoder(sample, fast_pass=True, patch_size=patch_size)\n"
        "        tokens = out['tokens_and_masks'].sentinel2_l2a\n"
        "        emb = tokens.mean(dim=[1, 2, 3, 4])\n"
        "    return emb.float().cpu().numpy()[0]"
    ))

    cells.append(md(f"## 5. Load OlmoEarth {model.capitalize()} encoder"))

    cells.append(code(
        "model = load_model_from_id(MODEL_ID)\n"
        "model.eval()\n"
        "encoder = model.encoder.to(device)\n"
        "n_params = sum(p.numel() for p in encoder.parameters())\n"
        'print(f"Loaded {MODEL_ID.name}: {n_params:,} params, embedding dim {EMBEDDING_DIM}")'
    ))

    cells.append(md("## 6. Extract embeddings for train + val"))

    cells.append(code(
        "def extract_all(windows, label_str):\n"
        "    embs, labels = [], []\n"
        "    for w in tqdm(windows, desc=label_str):\n"
        "        s2, lab = load_window_data(w, DATASET_PATH)\n"
        "        if s2 is None or lab is None or lab >= NUM_CLASSES:\n"
        "            continue\n"
        "        try:\n"
        "            embs.append(extract_embedding(encoder, s2, device))\n"
        "            labels.append(lab)\n"
        "        except Exception as e:\n"
        '            print(f"  skip {w.name}: {e}")\n'
        "            continue\n"
        "    return np.array(embs), np.array(labels)\n"
        "\n"
        'train_embeddings, train_labels = extract_all(train_windows, "Train")\n'
        'val_embeddings,   val_labels   = extract_all(val_windows,   "Val")\n'
        "\n"
        'print(f"Train: {train_embeddings.shape}, label dist: {Counter(train_labels.tolist())}")\n'
        'print(f"Val:   {val_embeddings.shape}, label dist: {Counter(val_labels.tolist())}")'
    ))

    cells.append(md(
        "## 7. Train classifiers\n"
        "\n"
        "- **kNN** with cosine similarity on L2-normalized embeddings (good for tiny datasets).\n"
        "- **Linear probe** (logistic regression) on StandardScaler-normalized embeddings (default).\n"
    ))

    cells.append(code(
        "# kNN (cosine, L2-normalized)\n"
        "train_norm = normalize(train_embeddings, norm='l2')\n"
        "val_norm   = normalize(val_embeddings,   norm='l2')\n"
        "k = min(KNN_K, len(train_embeddings))\n"
        "knn = KNeighborsClassifier(n_neighbors=k, metric='cosine').fit(train_norm, train_labels)\n"
        "knn_preds = knn.predict(val_norm)\n"
        "knn_acc = accuracy_score(val_labels, knn_preds)\n"
        'print(f"kNN  (k={k}, cosine): {knn_acc:.1%}")\n'
        "\n"
        "# Linear probe (StandardScaler-normalized)\n"
        "scaler = StandardScaler()\n"
        "train_scaled = np.nan_to_num(scaler.fit_transform(train_embeddings))\n"
        "val_scaled   = np.nan_to_num(scaler.transform(val_embeddings))\n"
        "lp = LogisticRegression(max_iter=1000, solver='lbfgs').fit(train_scaled, train_labels)\n"
        "lp_preds = lp.predict(val_scaled)\n"
        "lp_acc = accuracy_score(val_labels, lp_preds)\n"
        'print(f"Linear probe: {lp_acc:.1%}")'
    ))

    cells.append(md("## 8. Reports"))

    cells.append(code(
        'print("=== kNN report ===")\n'
        "print(classification_report(val_labels, knn_preds,\n"
        "                            labels=list(range(NUM_CLASSES)),\n"
        "                            target_names=CLASS_NAMES, zero_division=0))\n"
        'print("=== Linear probe report ===")\n'
        "print(classification_report(val_labels, lp_preds,\n"
        "                            labels=list(range(NUM_CLASSES)),\n"
        "                            target_names=CLASS_NAMES, zero_division=0))"
    ))

    cells.append(code(
        "import matplotlib.pyplot as plt\n"
        "\n"
        "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n"
        "for ax, preds, title in [(axes[0], knn_preds, 'kNN'),\n"
        "                          (axes[1], lp_preds, 'Linear probe')]:\n"
        "    cm = confusion_matrix(val_labels, preds, labels=list(range(NUM_CLASSES)))\n"
        "    ax.imshow(cm, cmap='Blues')\n"
        "    ax.set_title(f'{title} confusion matrix')\n"
        "    ax.set_xticks(range(NUM_CLASSES))\n"
        "    ax.set_yticks(range(NUM_CLASSES))\n"
        "    ax.set_xticklabels(CLASS_NAMES, rotation=45, ha='right')\n"
        "    ax.set_yticklabels(CLASS_NAMES)\n"
        "    for i in range(NUM_CLASSES):\n"
        "        for j in range(NUM_CLASSES):\n"
        "            ax.text(j, i, cm[i, j], ha='center', va='center',\n"
        "                    color='white' if cm[i, j] > cm.max() / 2 else 'black')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    cells.append(md(
        "## 9. Next steps\n"
        "\n"
        "- **If accuracy is good enough**: save the embeddings + classifier and you're done.\n"
        "  ```python\n"
        "  np.savez('embeddings.npz',\n"
        "           train_emb=train_embeddings, train_lab=train_labels,\n"
        "           val_emb=val_embeddings,     val_lab=val_labels)\n"
        "  import joblib; joblib.dump(lp, 'linear_probe.joblib')\n"
        "  ```\n"
        "\n"
        "- **If linear probe plateaus and you want more**: graduate to fine-tuning. "
        "See the AWF tutorial's Part B (`Fine-tuning OlmoEarth`) or `olmoearth_run` for "
        "the rslearn fine-tune pipeline. Budget 2–3 hours and ≥4 GB VRAM for a 30-epoch "
        "run; expect ~10–15 percentage points of accuracy over embeddings on a balanced task.\n"
        "\n"
        "- **If you want similarity search instead of classification**: skip the classifier "
        "and run cosine similarity directly on `val_norm` against `train_norm`.\n"
    ))

    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.10"},
        },
        "cells": cells,
    }


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate an OlmoEarth embeddings notebook.")
    p.add_argument("--dataset-path", required=True,
                   help="Path to the rslearn dataset directory.")
    p.add_argument("--num-classes", type=int, required=True,
                   help="Number of label classes.")
    p.add_argument("--class-names", default="",
                   help="Comma-separated class names, in label-ID order (0..N-1).")
    p.add_argument("--model", default="nano", choices=list(MODEL_IDS),
                   help="OlmoEarth model size.")
    p.add_argument("--train-group", default="train",
                   help="rslearn window group name for training set.")
    p.add_argument("--val-group", default="val",
                   help="rslearn window group name for validation set.")
    p.add_argument("--nodata", type=int, default=255,
                   help="Nodata sentinel in the label raster.")
    p.add_argument("--knn-k", type=int, default=20,
                   help="kNN neighbor count (capped at len(train) at runtime).")
    p.add_argument("--out", required=True,
                   help="Output .ipynb path.")
    args = p.parse_args(argv)

    if args.class_names:
        names = [n.strip() for n in args.class_names.split(",")]
        if len(names) != args.num_classes:
            print(
                f"--class-names has {len(names)} entries but --num-classes={args.num_classes}",
                file=sys.stderr,
            )
            return 2
    else:
        names = [f"class_{i}" for i in range(args.num_classes)]

    nb = build_notebook(
        dataset_path=args.dataset_path,
        num_classes=args.num_classes,
        class_names=names,
        model=args.model,
        train_group=args.train_group,
        val_group=args.val_group,
        nodata_value=args.nodata,
        knn_k=args.knn_k,
    )

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(nb, indent=1))
    print(f"Wrote {out} ({len(nb['cells'])} cells, {args.model} model, {args.num_classes} classes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
